RustCrypto/SSH

.github/workflows/workspace.yml
ssh-key/src/mpint.rs
ssh-key/src/reader.rs

Ensures the code is clippy-clean on the latest stable Rust release

ssh-key: bump clippy to Rust 1.64

---

Cargo.lock
ssh-key/Cargo.toml
ssh-key/src/private.rs
ssh-key/src/private/rsa.rs
ssh-key/src/public/rsa.rs
ssh-key/src/signature.rs

These releases have compatible sets of dependencies.
This PR uses a prerelease of the `rsa` crate as a compatible final release is not yet out.

ssh-key: bump `p256` => v0.11, `rsa` => `v0.7.0-rc.0`

---

README.md
ssh-key/README.md

There's now an SSH-specific Zulip stream:
https://rustcrypto.zulipchat.com/#narrow/stream/346919-SSH

README.md(s): update links to Zulip stream

---

.github/workflows/ssh-key.yml
Cargo.lock
ssh-key/Cargo.toml
ssh-key/README.md
ssh-key/src/public/rsa.rs

Uses namespaced features to eliminate superfluous "features" for optional dependencies, which should significantly improve CI build times when using `cargo hack`.
Also uses weak feature activation to activate the `std` features of relevant dependencies when the `ssh-key` crate's `std` feature is enabled.

Use namespaced/weak features; MSRV 1.60

---

ssh-key/Cargo.toml

The MSRV was bumped in #16, however that PR did not bump `rust-version`.

Cargo.toml: bump `rust-version` to 1.60

---

Cargo.lock
ssh-key/Cargo.toml

Changelog: https://github.com/RustCrypto/RSA/pull/211

Bump `rsa` to v0.7.0

---

Cargo.lock
ssh-key/Cargo.toml
ssh-key/src/private.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/signature.rs

Adds initial integration with the `p384` crate, including support for converting public and private keys to `p384` keys, as well as signing and verifying NIST P-384 signatures.

ssh-key: `p384` feature

---

Cargo.lock
ssh-key/Cargo.toml
ssh-key/README.md
ssh-key/src/mpint.rs
ssh-key/src/private/dsa.rs
ssh-key/src/public/dsa.rs
ssh-key/src/signature.rs

Adds an initial integration with the `dsa` crate including conversions to/from key types as well as signing and verification support.

ssh-key: DSA support

---

ssh-key/Cargo.toml
ssh-key/src/signature.rs

Eliminates the need for the `getrandom` feature in order to use `dsa`.
Uses RFC6979 deterministic DSA instead.

ssh-key: use deterministic `dsa` API

---

ssh-key/Cargo.toml
ssh-key/src/certificate.rs
ssh-key/src/certificate/builder.rs
ssh-key/src/certificate/unix_time.rs
ssh-key/src/fingerprint.rs
ssh-key/src/lib.rs
ssh-key/src/private.rs
ssh-key/src/public.rs
ssh-key/src/public/key_data.rs
ssh-key/src/writer.rs
ssh-key/tests/certificate.rs
ssh-key/tests/certificate_builder.rs
ssh-key/tests/public_key.rs

The relevant functionality is now enabled by default.
This cuts down on the number of features and overall feature-related complexity, especially as fingerprints are important baseline functionality.

ssh-key: remove `fingerprint` feature

---

ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs
ssh-encoding/src/reader.rs
ssh-key/src/certificate.rs
ssh-key/src/certificate/options_map.rs
ssh-key/src/kdf.rs
ssh-key/src/private.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/public/ed25519.rs
ssh-key/src/signature.rs
ssh-key/src/sshsig.rs

Changes the names of functions which operate on length-prefixed data to "prefixed", which more clearly communicates the behavior.

Rename `*nested*` to `*prefixed*`

---

ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs
ssh-encoding/src/lib.rs
ssh-key/src/private.rs
ssh-key/src/sshsig.rs

These traits provide a common implementation of decoding and encoding PEM documents which can be reused between OpenSSH private keys and the "sshsig" format.

ssh-encoding: add `DecodePem` and `EncodePem` traits

---

ssh-key/Cargo.toml
ssh-key/README.md
ssh-key/src/sshsig.rs

These static methods provide a low-level API which makes it easier to externalize signing methods more easily.

ssh-key: add `SshSig::new` and `::signed_data`

---

Cargo.lock
ssh-encoding/Cargo.toml
ssh-encoding/src/decode.rs
ssh-encoding/tests/decode.rs
ssh-encoding/tests/encode.rs

Adds tests for the `Decode` and `Encode` trait impls on various core Rust types.

ssh-encoding: add basic tests

---

ssh-encoding/src/lib.rs
ssh-encoding/src/writer.rs
ssh-key/src/certificate.rs
ssh-key/src/public.rs
ssh-key/src/public/ssh_format.rs

Unifies the logic for encoding public keys and certificates in the algorithm/key/comment "SSH-format", e.g.:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILM+rvN+ot98qgEN796jTiQfZfG1KaT0PtFDJ/XFSqti user@example.com
This removes the need for `base64_len_approx` to be located in the `ssh-encoding` crate.

ssh-key: unified pubkey/cert "SSH-format" encoder

---

ssh-encoding/src/encode.rs
ssh-encoding/src/lib.rs
ssh-key/src/private.rs
ssh-key/src/sshsig.rs

This commit adds a "heapless" mode for `EncodePem` which writes the encoded output to a provided buffer.
The old `EncodePem::encode_pem` method is renamed to `encode_pem_string` which is composed in terms of the new `::encode_pem` method.
This replaces the previous logic for doing this in the `ssh-key` crate.

ssh-encoding: unify PEM encoding in `EncodePem` trait

---

ssh-key/src/public.rs
ssh-key/src/public/ssh_format.rs

More consistent with other function signatures that put the output buffer as the last argument.

ssh-key: make `out` the last param of `public::SshFormat::encode`

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml

- `p384` feature ([#21])
- `dsa` feature ([#22], [#23])
- "[sshsig]" support ([#28])
- Bump `p256` to v0.11 ([#10])
- Bump MSRV to 1.60 ([#16])
- Bump `rsa` to v0.7 ([#20])
- Use `ssh-encoding` encoding crate ([#29], [#37])
- `fingerprint` feature removed, now always-on ([#27])
[#10]: https://github.com/RustCrypto/SSH/pull/10
[#16]: https://github.com/RustCrypto/SSH/pull/16
[#20]: https://github.com/RustCrypto/SSH/pull/20
[#21]: https://github.com/RustCrypto/SSH/pull/21
[#22]: https://github.com/RustCrypto/SSH/pull/22
[#23]: https://github.com/RustCrypto/SSH/pull/23
[#27]: https://github.com/RustCrypto/SSH/pull/27
[#28]: https://github.com/RustCrypto/SSH/pull/28
[#29]: https://github.com/RustCrypto/SSH/pull/29
[#37]: https://github.com/RustCrypto/SSH/pull/37
[sshsig]: …

ssh-key v0.5.0

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml

- README.md improvements ([#41])
[#41]: https://github.com/RustCrypto/SSH/pull/41

ssh-key v0.5.1

---

.github/workflows/ssh-key.yml

Possible workaround for the OOM issue

.github: perform `--release` build in CI

---

.github/workflows/ssh-key.yml
Cargo.lock
Cargo.toml
ssh-key/Cargo.toml
ssh-key/src/error.rs
ssh-key/src/lib.rs
ssh-key/src/mpint.rs
ssh-key/src/private.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/private/keypair.rs
ssh-key/src/private/rsa.rs
ssh-key/src/public/ed25519.rs
ssh-key/src/signature.rs
ssh-key/tests/certificate.rs
ssh-key/tests/encrypted_private_key.rs
ssh-key/tests/private_key.rs
ssh-key/tests/sshsig.rs

Also bumps crate version to v0.6.0-pre (unreleased) as this is a breaking change to the public API.

ssh-key: bump `signature` to v2.0.0-pre.3

---

Cargo.lock
Cargo.toml
ssh-key/Cargo.toml

Release notes: https://github.com/RustCrypto/traits/pull/1211
This also bumps the following crates:
- `dsa` v0.5
- `ed25519-dalek` "2.0" (via git)
- `p256` v0.12
- `p384` v0.12
- `rsa` v0.8 (via git)

Bump `signature` crate dependency to v2

---

ssh-key/src/signature.rs

Addresses a TODO about changing the error type for `TryFrom<&[u8]>` to `ssh_key::Error`, now that the `signature` crate's bounds have been changed in order to make that possible.

ssh-key: fix error type for `Signature` bytes conversion

---

.github/workflows/ssh-key.yml
.github/workflows/workspace.yml
Cargo.lock
ssh-encoding/src/error.rs
ssh-key/Cargo.toml
ssh-key/README.md
ssh-key/src/certificate.rs
ssh-key/src/error.rs
ssh-key/src/fingerprint.rs
ssh-key/src/known_hosts.rs
ssh-key/src/mpint.rs
ssh-key/src/private.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/public.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/public/ed25519.rs
ssh-key/src/signature.rs

Bumps the following dependencies:
- `bcrypt-pbkdf` v0.10
- `dsa` v0.6
- `p256` v0.13
- `p384` v0.13
- `rand_core` v0.6.4 (for `CryptoRngCore`)
- `sec1` v0.7

ssh-key: bump elliptic curve and password hash deps; MSRV 1.65

---

ssh-key/src/certificate/builder.rs
ssh-key/src/kdf.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/private/rsa.rs

Alias added in `rand_core` v0.6.4 with a blanket impl for `CryptoRng + RngCore`.
Using a mut reference avoids reborrowing.
For more context, see RustCrypto/traits#1148.

ssh-key: use `&mut impl CryptoRngCore` for RNGs

---

ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs
ssh-encoding/src/error.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/reader.rs
ssh-encoding/src/writer.rs

Automatically generate feature-specific annotations for documentation rather than relying on manual ones

ssh-encoding: use `doc_auto_cfg`

---

ssh-key/src/algorithm.rs
ssh-key/src/authorized_keys.rs
ssh-key/src/certificate.rs
ssh-key/src/certificate/builder.rs
ssh-key/src/cipher.rs
ssh-key/src/error.rs
ssh-key/src/fingerprint.rs
ssh-key/src/kdf.rs
ssh-key/src/known_hosts.rs
ssh-key/src/lib.rs
ssh-key/src/mpint.rs
ssh-key/src/private.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/private/keypair.rs
ssh-key/src/private/rsa.rs
ssh-key/src/private/sk.rs
ssh-key/src/public.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/public/ed25519.rs
ssh-key/src/public/key_data.rs
ssh-key/src/public/rsa.rs
ssh-key/src/public/sk.rs
ssh-key/src/signature.rs

Automatically generate feature-specific annotations for documentation rather than relying on manual ones

ssh-key: use `doc_auto_cfg`

---

ssh-key/src/certificate/builder.rs
ssh-key/tests/certificate_builder.rs

ssh-key: make `certificate::Builder::new` fallible

---

ssh-key/src/lib.rs
ssh-key/src/mpint.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/rsa.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/rsa.rs
ssh-key/src/signature.rs

From https://rust-lang.github.io/api-guidelines/naming.html
> In UpperCamelCase, acronyms and contractions of compound words count
> as one word: use Uuid rather than UUID, Usize rather than USize or
> Stdin rather than StdIn.
Based on that guidance, this renames the `Mpint` type accordingly.

ssh-key: rename `MPInt` => `Mpint`

---

ssh-key/README.md
ssh-key/src/fingerprint.rs
ssh-key/src/fingerprint/randomart.rs

Implements the "drunken bishop" algorithm described in this paper:
http://www.dirk-loss.de/sshvis/drunken_bishop.pdf
This algorithm produces hash visualizations like the following:
```
+--[ED25519 256]--+
|o+oO==+ o..      |
|.o++Eo+o..       |
|. +.oO.o . .     |
| . o..B.. . .    |
|  ...+ .S. o     |
|  .o. . . . .    |
|  o..    o       |
|   B      .      |
|  .o*            |
+----[SHA256]-----+
```

ssh-key: add "randomart" fingerprint visualizations

---

Cargo.lock
Cargo.toml
ssh-key/Cargo.toml

The latest release avoids superfluously pulling in the `pkcs8` dependency

ssh-key: use `ed25519-dalek` from git

---

ssh-key/src/private.rs
ssh-key/tests/encrypted_private_key.rs

Adds a method which provides control of the encryption cipher while still using a CSPRNG to generate unique checkints and KDF salts.

ssh-key: add `PrivateKey::encrypt_with_cipher`

---

ssh-key/src/algorithm.rs
ssh-key/src/certificate.rs
ssh-key/src/cipher.rs
ssh-key/src/error.rs
ssh-key/src/fingerprint.rs
ssh-key/src/kdf.rs
ssh-key/src/private.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/keypair.rs
ssh-key/src/public.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/public/key_data.rs
ssh-key/src/signature.rs
ssh-key/src/sshsig.rs

Splits the `Error` variants for unknown vs unsupported algorithms, propagating the `Algorithm` for the latter.
This helps identify which algorithm was unsupported, which can be used to inform what crate features need to be enabled.

ssh-key: split `AlgorithmUnknown` and `AlgorithmUnsupported`

---

ssh-key/src/error.rs
ssh-key/src/signature.rs

When the `std` feature is enabled, supports fully round tripping `ssh_key::Error` through `signature::Error` using
`signature::Error::from_source`.
This prevents important context from being lost, like if the error is due to an unsupported algorithm.

ssh-key: propagate `Error` through `signature::Error`

---

.github/workflows/ssh-key.yml
Cargo.lock
ssh-key/Cargo.toml
ssh-key/README.md
ssh-key/tests/certificate_builder.rs
ssh-key/tests/sshsig.rs

Adds a feature which enables cryptographic support without requiring users to enable specific algorithms.
It enables all available digital signature algorithms except for `dsa`, which is obsolete/weak.
It also enables the `aes-gcm` feature and transitively enables the `encryption` feature with support for encrypted private keys.
Also adds some documentation improvements.

ssh-key: add `crypto` feature

---

Cargo.lock
ssh-key/Cargo.toml
ssh-key/src/private/rsa.rs
ssh-key/src/public/rsa.rs

Release notes: https://github.com/RustCrypto/RSA/pull/318

ssh-key: bump `rsa` to v0.9

---

ssh-key/src/signature.rs
ssh-key/tests/sshsig.rs

This change implements the raw encoding and decoding of DSA signatures according to RFC4253 Section 6.6 instead of relying on the internal representation in the dsa crate. See #114 for additional detail.

Ensure DSA signatures are encoded according to spec

---

ssh-key/src/algorithm.rs
ssh-key/src/cipher.rs

This modification can make the codes more readable and fix clippy lints. Also, the derive Default on enums has been stabilized in Rust 1.62.0, which is lower than the current MSRV 1.65.0.

ssh-key: Replace Default impl with derive

---

ssh-encoding/src/encode.rs
ssh-encoding/src/error.rs
ssh-encoding/src/label.rs
ssh-encoding/src/lib.rs
ssh-key/src/algorithm.rs
ssh-key/src/certificate.rs
ssh-key/src/certificate/cert_type.rs
ssh-key/src/certificate/options_map.rs
ssh-key/src/certificate/unix_time.rs
ssh-key/src/cipher.rs
ssh-key/src/error.rs
ssh-key/src/kdf.rs
ssh-key/src/mpint.rs
ssh-key/src/private.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/private/keypair.rs
ssh-key/src/private/rsa.rs
ssh-key/src/private/sk.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/public/ed25519.rs
ssh-key/src/public/key_data.rs
ssh-key/src/public/rsa.rs
ssh-key/src/public/sk.rs
ssh-key/src/public/ssh_format.rs
ssh-key/src/signature.rs
ssh-key/src/sshsig.rs

Removes the associated `Encoding::Error` type as well as `Label::Error`, using `ssh_encoding::Error` as the type.
The rationale is error customization is primarily useful for decoding, not encoding. This change is a simplification.
Adds a `LabelError` type which captures the invalid label when the `alloc` feature has been enabled for display purposes. This is used as the error type for `FromStr` impls, so invalid labels can be propagated properly.

ssh-encoding: remove `Encoding::Error`; add `LabelError`

---

.github/workflows/ssh-cipher.yml
.github/workflows/ssh-key.yml
Cargo.lock
Cargo.toml
ssh-cipher/CHANGELOG.md
ssh-cipher/Cargo.toml
ssh-cipher/LICENSE-APACHE
ssh-cipher/LICENSE-MIT
ssh-cipher/README.md
ssh-cipher/src/lib.rs
ssh-key/Cargo.toml
ssh-key/LICENSE-MIT
ssh-key/src/error.rs
ssh-key/src/lib.rs
ssh-key/src/private.rs
ssh-key/tests/encrypted_private_key.rs

Extracts symmetric encryption support into its own `ssh-cipher` crate which can be used independently from `ssh-key`.

ssh-cipher: extract from `ssh-key`

---

ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/lib.rs
ssh-key/tests/encrypted_private_key.rs

Refactors the implementation of the chacha20-poly1305@openssh.com variant of ChaCha20Poly1305 into a struct which stores instances of `ChaCha20` and `Poly1305`.

ssh-cipher: refactor ChaCha20Poly1305 implementation

---

ssh-key/src/public.rs

There was a copy and paste error in the docs for the function PublicKey::key_data, which said that it would return the private key. ( I hope this was a mistake and not an new attack against ssh keys)

Corrected the docs to say public key

---

Cargo.lock
ssh-encoding/Cargo.toml
ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs

Adds (optional) support for decoding/encoding `bytes::Bytes` as `byte[n]`.

ssh-encoding: `bytes` feature

---

ssh-key/src/algorithm.rs
ssh-key/src/algorithm/name.rs
ssh-key/src/certificate.rs
ssh-key/tests/algorithm_name.rs

Only computes the certificate algorithm identifier when needed as opposed to eagerly.

ssh-key: lazily compute `AlgorithmName::certificate_type`

---

ssh-key/src/certificate/builder.rs
ssh-key/tests/certificate_builder.rs

It previously had the `valid_after` and `valid_before` arguments swapped, which would've caused errors with expected usage.
This commit adds a test that confirmed the certificate builder initializes successfully after swapping the arguments back.
Closes #142

ssh-key: fix `certificate::Builder::new_with_validity_times`

---

ssh-key/src/mpint.rs
ssh-key/src/public.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/public/key_data.rs
ssh-key/src/public/opaque.rs
ssh-key/src/public/rsa.rs
ssh-key/src/public/sk.rs
ssh-key/tests/public_key.rs

Implementing the Hash trait enables using PublicKeys and relatives as HashMap keys and in HashSets.

ssh-key: have PublicKey and its parts implment Hash

---

ssh-cipher/Cargo.toml
ssh-encoding/CHANGELOG.md
ssh-encoding/Cargo.toml
ssh-key/Cargo.toml

- `LabelError` ([#124])
- `bytes` feature ([#138])
- Bump `pem-rfc7468` to v0.7 ([#84])
- `Encoding::Error` ([#124])
[#84]: https://github.com/RustCrypto/SSH/pull/84
[#124]: https://github.com/RustCrypto/SSH/pull/124
[#138]: https://github.com/RustCrypto/SSH/pull/138

ssh-encoding v0.2.0

---

ssh-key/src/mpint.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/key_data.rs
ssh-key/src/public/rsa.rs

Don't impl `Hash` on `Mpint` which contains potentially secret data. Instead, have the caller determine if a particular `Mpint` is safe to `Hash` and then explicitly pass its data to the relevant `Hasher`.

ssh-key: `Hash` impl cleanups

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml

- Partial support for U2F signature verification ([#44])
- Support for `aes256-gcm@openssh.com` encryption ([#75])
- "randomart" public key fingerprint visualizations ([#77])
- `PrivateKey::encrypt_with_cipher` ([#79])
- Propagate `ssh_key::Error` through `signature::Error` ([#82])
- `crypto` feature ([#83])
- Support for AES-CBC, ChaCha20Poly1305, and TDES encryption ([#118])
- Basic support for nonstandard SSH key algorithms ([#136])
- Impl `Hash` for `PublicKey` and its parts ([#145], [#149])
- Bump `signature` crate dependency to v2 ([#58])
- Use `ssh_key::Error` as error type for `TryFrom<&[u8]>` impl on `Signature` ([#59])
- Bump elliptic curve and password hash deps; MSRV 1.65 ([#66])
- `bcrypt-pbkdf` v0.10
- `dsa` v0.6
- `p256` v0.13
- `p384` v0.13
- `sec1` v0.7
- Use `&mut impl …

ssh-key v0.6.0

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml

- `minimal-versions` correctness for `sec1` dependency ([#154])
[#154]: https://github.com/RustCrypto/SSH/pull/154

ssh-key v0.6.1

---

ssh-key/src/public.rs
ssh-key/src/sshsig.rs

Provides a complete example for how to use `PublicKey::verify`

ssh-key: add `SshSig` signature verification example

---

ssh-key/src/private.rs
ssh-key/src/public.rs
ssh-key/src/sshsig.rs

Complements #166 with an example for how to produce signatures

ssh-key: add `SshSig` signing example

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml
ssh-key/src/lib.rs

- `SshSig` usage examples ([#166], [#167])
[#166]: https://github.com/RustCrypto/SSH/pull/166
[#167]: https://github.com/RustCrypto/SSH/pull/167

ssh-key v0.6.2

---

ssh-key/src/mpint.rs
ssh-key/src/signature.rs

Changes the method to allow leading zeroes, stripping them and readding a leading one if need be.
Closes #170

ssh-key: handle leading zeroes in `Mpint::from_positive_bytes`

---

ssh-key/src/signature.rs
ssh-key/tests/examples/id_sk_ecdsa_p256_2.pub
ssh-key/tests/sshsig.rs

I recently obtained a Yubikey Series 5 hardware token with the ability to generate and use sk-ecdsa type keys with openssh. It seemed like a good addition to the ssh-key crate to implement validation of signatures generated using such keys, as this is not yet supported and depending on firmware version of the hardware token, this is sometimes the only key type it can handle.
The signature is generated with OpenSSH_9.5p1 tools and the resulting signature is captured using my https://github.com/nresare/ssh-agent-client-rs library
I have made some slightly more opinionated changes compared to last time around, breaking out shared functionality into private helper functions in signature.rs. Just let me know what you think, and I'm happy to restructure to match your preferences.

ssh-key: Implement SkEcdsaSha2NistP256 signature validation

---

ssh-key/src/certificate/unix_time.rs

`ssh-keygen` uses `i64::MAX` as its placeholder value for certificates which last "forever".
This allows such certificates to parse, albeit at the cost of allowing all sorts of bogus timestamps.
Closes #174

ssh-key: set maximum `UnixTime` to `i64::MAX`

---

.github/workflows/ssh-key.yml
Cargo.lock
ssh-key/Cargo.toml
ssh-key/src/private.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/public/ecdsa.rs
ssh-key/src/signature.rs

Adds initial integration with the `p521` crate, including support for converting public and private keys to `p521` keys, as well as signing and verifying NIST P-521 signatures.
Note that there's a lot of redundancy/boilerplate repeated for `p256`, `p384`, and `p521` it would be nice to eventually DRY out, possibly using macros to write the impls.

ssh-key: `p521` feature

---

ssh-key/src/public/ecdsa.rs
ssh-key/src/signature.rs

Adds some macros which write the boilerplate trait impls for each curve

ssh-key: DRY out ECDSA impls with `macro_rules!`

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml
ssh-key/README.md

- `SkEcdsaSha2NistP256` signature validation ([#169])
- `p521` feature ([#180])
- Maximum certificate timestamp time is now `i64::MAX` ([#175])
- Handle leading zeroes in `Mpint::from_positive_bytes` ([#171])
[#169]: https://github.com/RustCrypto/SSH/pull/169
[#171]: https://github.com/RustCrypto/SSH/pull/171
[#175]: https://github.com/RustCrypto/SSH/pull/175
[#180]: https://github.com/RustCrypto/SSH/pull/180

ssh-key v0.6.3

---

ssh-key/src/public.rs
ssh-key/tests/private_key.rs
ssh-key/tests/public_key.rs

Also adds an integration test to ensure that the file output matches what `ssh-keygen` generates byte-for-byte.
The `ToString` impl still omits the newline.
To avoid making breaking changes, it always uses `\n` as the newline, however perhaps in a future breaking release it could be changed to accept `LineEnding` so as to match `PrivateKey::write_openssh_file`.
Fixes #187.

Add newline to `PublicKey::write_openssh_file` output

---

ssh-key/src/signature.rs

This allows Signatures with `Algorithm::Other`. The only restriction is that the passed-in data must not be empty. The AlgorithmLabel already requires that the name follows [RFC 4251](https://www.rfc-editor.org/rfc/rfc4251.html#page-10) for "additional algorithms" meaning they have a algorithm name and an '@' followed by a domain.

ssh-key: add Algorithm::Other Signature support

---

ssh-key/src/signature.rs

The integer components `r` and `s` of the generated signature may be less than 160 bits, which is the exact length required by SSH wire format.
This commit fixes #190 by padding the integer components with leading zeros to make them 160 bits long.

ssh-key: fix DsaKeypair::try_sign format error

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml
ssh-key/LICENSE-MIT

- `Algorithm::Other` signature support ([#189])
- Add newline to `PublicKey::write_openssh_file` output ([#188])
- `DsaKeypair::try_sign` format error ([#191])
[#188]: https://github.com/RustCrypto/SSH/pull/188
[#189]: https://github.com/RustCrypto/SSH/pull/189
[#191]: https://github.com/RustCrypto/SSH/pull/191

ssh-key v0.6.4

---

ssh-key/src/signature.rs

The elliptic curve was misspecified for `p384::ecdsa::Signature` and `p521::ecdsa::Signature`.
Additionally P-521 had an incorrect field size.
Closes #197

ssh-key: correct erroneous signature constants

---

ssh-key/src/error.rs
ssh-key/src/private/sk.rs
ssh-key/src/public/sk.rs
ssh-key/tests/public_key.rs

Introducing draft of `SkEcdsaSha2NistP256::new()` and `SkEd25519::new()`. It's just public keys, code for private keys would eventually follow.
Based on https://github.com/RustCrypto/SSH/issues/200, would this be a way to go?

Sk constructors

---

ssh-key/src/error.rs
ssh-key/src/private/sk.rs

Uses an existing error type for these constructors, rather than adding a new one.

ssh-key: return `encoding::Error::Length` from `Sk*` constructors

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml

- `Sk*` constructors ([#201], [#204])
- Simplify DSA signature encoding ([#193])
- Correct erroneous signature constants ([#202])
[#193]: https://github.com/RustCrypto/SSH/pull/193
[#201]: https://github.com/RustCrypto/SSH/pull/201
[#202]: https://github.com/RustCrypto/SSH/pull/202
[#204]: https://github.com/RustCrypto/SSH/pull/204

ssh-key v0.6.5

---

ssh-key/README.md

Several OpenSSH-specific formats were previously described as "SSH".
This commit changes the ones that are only in OpenSSH to be "OpenSSH", and only uses "SSH" for formats with pre-OpenSSH support.

README.md: clarify SSH vs OpenSSH formats

---

ssh-key/src/certificate/options_map.rs
ssh-key/tests/certificate.rs

There was recent clarification on how critical options values should be read: https://bugzilla.mindrot.org/show_bug.cgi?id=2389
The gist of it is that values can be of any kind, but they generally are strings. To support more types, the value is encoded in a more generic way. For a string, this means there are 2 length prefixes (4 bytes for the total length of the value and then 4 bytes for the length of the string).
This PR aims at fixing this issue.

Critical options String values double-length encoding

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-encoding/Cargo.toml
ssh-key/Cargo.toml
ssh-key/src/authorized_keys.rs
ssh-key/src/certificate.rs
ssh-key/src/certificate/builder.rs
ssh-key/src/known_hosts.rs

Closes #174
Previously certificates only supported the `i64` range to allow for infallible conversions to/from `SystemTime`.
Unfortunately OpenSSH defaults to using `u64::MAX` as the `valid_before` time in order to represent certificate that's valid "forever". The previous restriction meant that `ssh-key` was incapible of parsing such certificates.
This commit switches to using a raw `u64` everywhere, and changing conversions to `SystemTime` to return an `Option<SystemTime>` which is `None` if the `u64` value overflows an `i64`.

ssh-key: use `u64` type for certificate timestamps

---

ssh-key/src/private/keypair.rs

When parsing ssh keys from the SSH agent protocol, you need to read the first element of the protocol (the [`ssh_key::Algorithm`](https://docs.rs/ssh-key/latest/ssh_key/enum.Algorithm.html) (encoded as a String) to make a decision whether what comes next is supposed to be parsed as an [`ssh_key::Certificate`](https://docs.rs/ssh-key/latest/ssh_key/certificate/struct.Certificate.html) or as an [`ssh_key::private::KeypairData`](https://docs.rs/ssh-key/latest/ssh_key/private/enum.KeypairData.html).
Because the content has already been consumed from the reader, and because you can't go backwards in the reader. This requires `decode_as` to be exposed on `ssh_key::private::KeypairData`.

ssh-key: make `decode_as` a public API 

---

ssh-key/CHANGELOG.md

Added:
- impl `decode_as` for `KeypairData` ([#211])
Changed:
- clarify SSH vs OpenSSH formats ([#206])
Fixed:
- fix `certificate::OptionsMap` encoding ([#207])
- fixup `EcdsaPrivateKey` Debug impl ([#210])
[#206]: https://github.com/RustCrypto/SSH/pull/206
[#207]: https://github.com/RustCrypto/SSH/pull/207
[#210]: https://github.com/RustCrypto/SSH/pull/210
[#211]: https://github.com/RustCrypto/SSH/pull/211

ssh-key: v0.6.6

---

ssh-encoding/src/decode.rs

The previous comment seems to have been a copy-pasta from the previous method, because reading Vec<u8> follows the logic for string reading (LV) rather than pre-defined length, which is how byte[] works.

Fix comment for Vec<u8> decoding

---

ssh-key/src/private/rsa.rs

The conversion to `rsa::RsaPrivateKey` currently supplies the prime p twice rather than using prime p and q respectively.

ssh-key/rsa.rs: Fix double use of prime p in conversion

---

ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs
ssh-encoding/tests/decode.rs
ssh-encoding/tests/encode.rs

This PR adds `Encode` and `Decode` traits for `boolean` types, as described in [RFC4251 § 5](https://datatracker.ietf.org/doc/html/rfc4251#section-5).
This is a pretty simple type (encodes as `0u8` or `1u8`) but adding for completeness.

Add 'boolean' encode/decode support (ssh-encoding)

---

ssh-encoding/Cargo.toml
ssh-encoding/src/error.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/reader.rs
ssh-encoding/src/reader/base64.rs
ssh-encoding/src/writer.rs
ssh-encoding/src/writer/base64.rs

Also factors them into internal submodules.
This provides greater future flexibility around these types.

ssh-encoding: `Base64Reader`/`Base64Writer` newtypes

---

ssh-encoding/src/base64.rs
ssh-encoding/src/base64/reader.rs
ssh-encoding/src/base64/writer.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/reader.rs
ssh-encoding/src/writer.rs

Moves all Base64-related encoding support into a `base64` module

ssh-encoding: extract a `base64` module

---

ssh-encoding/Cargo.toml
ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs
ssh-encoding/src/error.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/pem.rs
ssh-encoding/src/pem/decode.rs
ssh-encoding/src/pem/encode.rs
ssh-encoding/src/pem/reader.rs
ssh-encoding/src/pem/writer.rs
ssh-encoding/src/reader.rs
ssh-encoding/src/writer.rs
ssh-key/src/lib.rs

Ala #220, but for PEM, creates newtypes implementing the `Reader` and `Writer` traits for greater future flexibility around these types.
Also factors them into internal submodules.

ssh-encoding: internal `PemReader`/`PemWriter` newtypes

---

ssh-cipher/src/lib.rs
ssh-encoding/src/lib.rs
ssh-key/src/authorized_keys.rs
ssh-key/src/certificate/unix_time.rs
ssh-key/src/lib.rs

Helps ensure code remains friendly to heapless/alloc-only targets

clippy: add import lints for `core`/`alloc`/`std`

---

.github/workflows/ssh-key.yml
Cargo.lock
ssh-key/Cargo.toml

It was needed before `p521` had RFC6979 support, but is no longer necessary.

ssh-key: disable `p521` getrandom feature

---

ssh-encoding/src/base64/reader.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/pem/reader.rs
ssh-encoding/src/reader.rs

Changes `Reader::read_prefixed` from a provided method to one which must be impl'd by all of the `Reader` types, of which there are currently three:
- `&[u8]`
- `Base64Reader`
- `PemReader`
This should reduce monomorphization bloat from `NestedReader` which encapsulates other reader types, including other `NestedReader`s, depending on the level of nesting, which is generally low, but good to eliminate entirely.
This does lead to a small amount of duplication between `Base64Reader` and `PemReader` which was previously encapsulated in `NestedReader`. It can possibly be eliminated in followup work.

ssh-encoding: remove `NestedReader`

---

.github/workflows/ssh-key.yml

The combinatorial explosion of features is leading to long CI times.
This reduces the number of combinations checked to something more manageable.

ssh-key: reduce CI `no_std` build combos

---

ssh-cipher/Cargo.toml
ssh-encoding/Cargo.toml
ssh-key/Cargo.toml

This tweaks the `repository` fields in Cargo metadata in order to use the correct (i.e. git clonable) URL. The existing GitHub webUI URLs for each package have been retained and moved to `homepage` fields.

cargo: point `repository` metadata to clonable URLs

---

.github/workflows/ssh-derive.yml
Cargo.lock
Cargo.toml
README.md
ssh-derive/CHANGELOG.md
ssh-derive/Cargo.toml
ssh-derive/LICENSE-APACHE
ssh-derive/LICENSE-MIT
ssh-derive/README.md
ssh-derive/src/decode.rs
ssh-derive/src/decode/field.rs
ssh-derive/src/encode.rs
ssh-derive/src/field_ir.rs
ssh-derive/src/lib.rs

Adds a basic implementation with support for deriving the `Decode` and `Encode` traits.

ssh-derive: initial implementation

---

ssh-key/src/certificate.rs
ssh-key/src/public/key_data.rs

This additional function is needed for SSH Agent Protocol where, based on
the algorithm, we need to parse the `Certificate` or the `KeyData`.
Without `decode_as` the `decode` function will greedily consume additional
string from the reader.
This is similar to https://github.com/RustCrypto/SSH/pull/211.
See: https://github.com/wiktor-k/ssh-agent-lib/issues/83

ssh-key: Add `Certificate::decode_as` and expose `KeyData::decode_as`

---

Cargo.lock
Cargo.toml
ssh-cipher/Cargo.toml
ssh-encoding/Cargo.toml
ssh-key/Cargo.toml

Bumps the following to the latest prerelease versions:
- `aes` v0.9.0-pre.1
- `aes-gcm` v0.11.0-pre.1
- `bcrypt-pbkdf` v0.11.0-pre.1
- `cbc` v0.2.0-pre.1
- `chacha20` v0.10.0-pre.1
- `ctr` v0.10.0-pre.1
- `des` v0.9.0-pre.1
- `dsa` v0.7.0-pre.0
- `ecdsa` v0.17.0-pre.7
- `ed25519` v2.3.0-pre.0
- `ed25519-dalek` v2.2.0-pre (sourced from git)
- `p256` v0.14.0-pre.1
- `p384` v0.14.0-pre.1
- `p521` v0.14.0-pre.1
- `pbkdf2` v0.13.0-pre.1
- `pem-rfc7468` v1.0.0-rc.0
- `rsa` v0.10.0-pre.2
- `sha2` v0.11.0-pre.4
- `signature` v2.3.0-pre.4

Use new prereleases

---

.github/workflows/ssh-key.yml
Cargo.lock
Cargo.toml
ssh-key/Cargo.toml
ssh-key/src/lib.rs
ssh-key/tests/certificate.rs
ssh-key/tests/certificate_builder.rs
ssh-key/tests/sshsig.rs

This makes it possible to publish a prerelease, which we otherwise can't do since we're sourcing `ed25519-dalek` from this git branch:
https://github.com/dalek-cryptography/curve25519-dalek/pull/676
This commit can be reverted immediately after we publish a crate release.

ssh-key: temporarily remove `ed25519` feature

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-encoding/Cargo.toml
ssh-key/Cargo.toml
ssh-protocol/Cargo.toml

Publishes an initial set of prereleases of the following crates:
- `ssh-cipher` v0.3.0-pre.0
- `ssh-encoding` v0.3.0-pre.0
- `ssh-key` v0.7.0-pre.0
- `ssh-protocol` v0.1.0-pre.0

Publish `pre.0` prereleases

---

.github/workflows/ssh-key.yml
Cargo.lock
Cargo.toml
ssh-key/Cargo.toml
ssh-key/src/lib.rs
ssh-key/tests/certificate.rs
ssh-key/tests/certificate_builder.rs
ssh-key/tests/sshsig.rs

This reverts commit d52ad0b6f81458c21192ede8c2ad14f97bbb3b3e.
Now that we've cut a set of prereleaes (#250) we can add the `ed25519` feature back.

Revert "ssh-key: temporarily remove `ed25519` feature (#249)"

---

ssh-cipher/src/decryptor.rs
ssh-cipher/src/encryptor.rs
ssh-cipher/src/lib.rs

Adds stateful types which can incrementally decrypt/encrypt data in CBC or CTR modes.
Closes #164

ssh-cipher: add `Decryptor` and `Encryptor`

---

ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/lib.rs
ssh-key/src/kdf.rs

In the OpenSSH protocol, ChaCha20Poly1305 uses two different keys: one for length encryption, and one for payloads.
It wasn't previously possible to use both keys (or at least quite obtuse) because `ssh-cipher` chopped up `k_1` and `k_2` and only allowed `k_1` to be used.
This change hoists that into `ssh-key` for file encryption uses, giving access to the raw `ChaCha20Poly1305` implementation and allowing use of either key.
In addition, a nonce is now mandatory, but use of the default all-zero nonce for file encryption purposes is now handled in `ssh-key`.

ssh-cipher: make ChaCha20Poly1305 accept a 256-bit key

---

ssh-cipher/src/decryptor.rs
ssh-cipher/src/encryptor.rs
ssh-cipher/src/error.rs
ssh-cipher/src/lib.rs
ssh-key/src/kdf.rs

Adds an `Error::Length` variant and returns it whenever the input buffer for an encryption/decryption operation is not properly aligned to the cipher's block size.
Also adds a private `Cipher::check_key_and_iv` method to validate keys/IVs are the expected size and return appropriate erros if they are not.

ssh-cipher: length handling improvements

---

ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/lib.rs

Directly exposes the `ChaCha20Poly1305` type implementing the `chacha20-poly1305@openssh.com` variant (which is different from the NaCl/libsodium "djb" variant as well as the IETF variant of ChaCha20Poly1305).
Also improves documentation to help clarify its nature.

ssh-cipher: make `ChaCha20Poly1305` public

---

Cargo.lock
ssh-key/Cargo.toml
ssh-key/src/dot_ssh.rs
ssh-key/src/lib.rs
ssh-key/tests/dot_ssh.rs

Adds a type for interacting with a user's `~/.ssh` directory, including the following functionality:
- Locating the configuration file
- Iterating over private keys
- Iterating over public keys
- Finding a private key with a given fingerprint
- Finding a public key with a given fingerprint

ssh-key: add `DotSsh`

---

ssh-key/src/dot_ssh.rs

Adds helpers for writing private/public key files into `~/.ssh`

ssh-key: add `DotSsh::{write_private_key, write_public_key}`

---

ssh-key/src/signature.rs

These were previously rejected with `Error::Length`.
This change allows parsing them, however verification will still fail.
Closes #262

ssh-key: support for parsing legacy SHA-1 RSA signatures

---

ssh-cipher/src/decryptor.rs

When decrypting messages from the wire, we need to first decrypt the first couple of bytes (4 or 16 bytes) just to get the length of packet.
Once we get the length of the packet we can decrypt the full payload. If we just used the Decryptor api as it is, we would alter the internal state.

ssh-cipher: allows to decrypt a payload without altering state

---

ssh-key/src/sshsig.rs

Hello
I'm making a web server, which operates on SSH signatures, and I noticed that I could not include `SshSig` in my Serde Deserialized struct, so I had to parse it manually. So I decided to fork and add this functionality.
Cheers!

ssh-key: add `SshSig` serializing/deserializing using `serde`

---

ssh-key/src/mpint.rs
ssh-key/src/private/rsa.rs
ssh-key/src/public/rsa.rs
ssh-key/tests/certificate.rs
ssh-key/tests/private_key.rs
ssh-key/tests/public_key.rs

Additionally:
- Adds `Mpint::is_positive`
- Ensures `e` and `n` values of `RsaPublicKey` are always positive
Closes #261

ssh-key: make `RsaPublicKey` fields private; add `key_size`

---

Cargo.lock
ssh-encoding/Cargo.toml
ssh-encoding/src/lib.rs
ssh-encoding/src/writer.rs
ssh-key/src/fingerprint.rs

This allows to write to the digest directly from the serializer.

ssh-encoding: adds a `DigestWriter`

---

.github/workflows/ssh-encoding.yml
ssh-encoding/Cargo.toml
ssh-encoding/README.md

The MSRV was increased due to the `digest` dependency in #268

ssh-encoding: MSRV 1.71

---

Cargo.lock
ssh-encoding/Cargo.toml
ssh-encoding/src/lib.rs
ssh-encoding/src/writer.rs
ssh-key/Cargo.toml

- Makes `digest` optional the same way `sha2` was optional
- `sha2` is no-longer used by `ssh-encoding`; generic around `digest`

ssh-encoding: add `digest` feature; remove `sha2` dep

---

ssh-key/src/private/keypair.rs
ssh-key/src/private/rsa.rs
ssh-key/tests/private_key.rs

Also adds fallible constructors, and uses those in the `Decode` impls.
The new constructors ensure the provided `Mpint`s are non-negative.

ssh-key: make all RSA private key fields private

---

ssh-key/src/private/dsa.rs
ssh-key/src/private/keypair.rs
ssh-key/src/public/dsa.rs
ssh-key/src/signature.rs
ssh-key/tests/certificate.rs
ssh-key/tests/private_key.rs
ssh-key/tests/public_key.rs

Like we did for RSA in #274, this makes all fields of DSA keys private, and also validates that their inner `Mpint`s are positive.

ssh-key: make all DSA key fields private

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/lib.rs
ssh-key/src/kdf.rs

Changes the `ChaCha20Poly1305` type to impl the standard AEAD APIs exported by the `aead` crate.

ssh-cipher: refactor `ChaCha20Poly1305` to use `aead` API

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/lib.rs

From PROTOCOL.chacha20poly1305:
> Once the entire packet has been received, the MAC MUST be checked
> before decryption. A per-packet Poly1305 key is generated as described
> above and the MAC tag calculated using Poly1305 with this key over the
> ciphertext of the packet length and the payload together.
This implements AAD which pads the input to the Poly1305 block size, inputting it first before the ciphertext.
~~It should be sufficient for SSH packet encryption use cases, although unfortunately we have no test vectors other than the ones in the `ssh-key` crate (which are unaffected by this change).~~ Test vectors added.
Closes #279

ssh-cipher: add AAD support to `ChaCha20Poly1305`

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-cipher/src/chacha20poly1305.rs
ssh-key/Cargo.toml

Adds a feature which transitively enables zeroization support in various dependencies.
`ssh-key` now activates it by default.

ssh-cipher: add `zeroize` feature

---

ssh-key/src/authorized_keys.rs

Treat 3 or more spaces the same. Comments start at the space and continue to the end of the line.
Closes #285

ssh-key: allow `AuthorizedKeys` comments to have spaces

---

ssh-key/src/signature.rs

Leading zeros must be stripped from `mpint` values (per [RFC 4251](https://datatracker.ietf.org/doc/html/rfc4251#section-5)), meaning it's possible to see "short" `mpint` values when using them to construct signatures.
These values must be padded with leading zeros before being used in `pXYZ::ecdsa::Signature`, which expect exact-size arrays.
See #290 for details.

ssh-key: accept undersized mpints in ECDSA signatures

---

FUNDING.json

Add Open Source Collective-owned wallet to collect funds on behalf of rustcrypto/ssh

Add OSC-owned eth address for drips

---

Cargo.lock
ssh-key/CHANGELOG.md
ssh-key/Cargo.toml

- Parsing `AuthorizedKeys` with whitespace in comments ([#289])
- `mpint` decoding in ECDSA signatures ([#290], [#291])
[#289]: https://github.com/RustCrypto/SSH/pull/289
[#290]: https://github.com/RustCrypto/SSH/pull/290
[#291]: https://github.com/RustCrypto/SSH/pull/291

ssh-key v0.6.7

---

ssh-key/CHANGELOG.md

These releases were performed on the `stable` branch. See #302.

ssh-key: add CHANGELOG.md entries vor v0.6.6+v0.6.7

---

.github/workflows/ssh-cipher.yml
.github/workflows/ssh-encoding.yml
.github/workflows/ssh-key.yml
.github/workflows/ssh-protocol.yml
.github/workflows/workspace.yml
Cargo.lock
ssh-cipher/Cargo.toml
ssh-cipher/README.md
ssh-cipher/src/error.rs
ssh-cipher/src/lib.rs
ssh-encoding/Cargo.toml
ssh-encoding/README.md
ssh-encoding/src/error.rs
ssh-encoding/src/label.rs
ssh-encoding/src/lib.rs
ssh-key/Cargo.toml
ssh-key/README.md
ssh-key/src/error.rs
ssh-protocol/Cargo.toml
ssh-protocol/README.md

Now that `core::error::Error` is stable in 1.81, leverages it to make the `Error` impl always available.
Since `ssh-cipher` has no other dependencies on `std`, removes the `std` feature from this crate entirely.

Leverage `core::error::Error`; MSRV 1.81

---

ssh-key/src/signature.rs

This is just a simple documentation fix.

ssh-key: fix documentation typo

---

ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs
ssh-encoding/tests/decode.rs
ssh-encoding/tests/encode.rs
ssh-key/src/public/ed25519.rs

The type `[u8; N]` maps naturally to SSH's `byte[n]` type, which has no length prefix because `n` is known a priori.
In cases where `[u8; N]` is being used to store an SSH `string`, such as Ed25519 public keys, it first needs to be converted to `[u8]` (which maps to `string`) using `as_slice()`

ssh-encoding: remove length prefix from `[u8; N]` encoding

---

ssh-encoding/src/decode.rs
ssh-encoding/src/encode.rs

The impls of `Decode` for `Bytes` and `Encode` for `[u8]` made reference to `byte[n]`, i.e. a fixed length bytestring, however both these types are analogues for `string`, which is encoded with a length prefix.
The comments have been updated to reflect the correct type they map to in the SSH encoding schema, which is `string`.

ssh-encoding: fix `string` comments on encoding trait impls

---

ssh-key/src/public.rs

Note that "comment" is only carried with the string serialization of `PublicKey`.
Fixes #340

ssh-key: add `serde` comment about `PublicKey`

---

ssh-derive/src/decode.rs
ssh-derive/src/encode.rs

The previous code would panic for structs with more than one field, and was dependent on certain traits being visible. This should now be fixed. I find testing derive macros a bit painful. Instead some doctests in the consuming crate `ssh-encoding` could serve as implicit integration tests. I'll add a PR for that if/when this one is resolved.
I haven't done anything in terms of configuration, so this only fixes the functionality that was intended already. I.e. the `ssh` macro attribute is still unused.

ssh-derive: fix derive macros for `Encode` and `Decode`

---

ssh-encoding/src/encode.rs

Followup to #342, which only updated the `encode` method. This aligns the `encoded_len` method with that change.

ssh-encoding: fix `encoded_len` for `[u8; N]`

---

ssh-key/src/private/rsa.rs

Shoutout to @dignifiedquire for finding the issue in https://github.com/RustCrypto/RSA/issues/463

Fix primes on RSA key conversion

---

ssh-encoding/src/lib.rs

Adds an overview of the data types and their associated wire formats implemented by this crate, adapting the text from RFC4251.

ssh-encoding: add RFC4251-derived documentation

---

ssh-key/src/private/ecdsa.rs
ssh-key/tests/private_key.rs

- fixes #350 
- I still need to investigate key encoding to ensure code is even remotely correct

ssh-key: support for undersized ECDSA/P-521 keys

---

ssh-key/src/signature.rs

> [!IMPORTANT]
>  This PR is branched from #315 and depends on it 
fixes #322
This PR implements `Signer` for `(&RsaKeypair, Option<HashAlg>)`. I'm not happy about the API, but I wanted to avoid creating a new trait just for this. Open to suggestions.

ssh-key: support making RSA-SHA1 signatures

---

ssh-key/src/private/ecdsa.rs
ssh-key/tests/private_key.rs

Followup to #351
Also includes a fix and test to ensure that short keys zero-pad MSB rather than LSB, since they're encoded as big endian.

ssh-key: simplified ECDSA private key decoding logic

---

ssh-encoding/src/decode.rs
ssh-encoding/src/lib.rs

For the listing of RFC4251 types, uses better headings for each type, and adds a list of types which have compatible `Decode`/`Encode` impls

ssh-encoding: improve rustdoc

---

Cargo.lock
ssh-encoding/Cargo.toml
ssh-encoding/src/error.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/mpint.rs
ssh-key/Cargo.toml
ssh-key/src/lib.rs
ssh-key/src/private/dsa.rs

This makes it possible to support the `mpint` data type encoding in other applications than just `ssh-key`.

Move `Mpint` from `ssh-key` to `ssh-encoding`

---

ssh-key/src/comment.rs
ssh-key/src/lib.rs
ssh-key/src/private.rs
ssh-key/src/public.rs
ssh-key/tests/authorized_keys.rs
ssh-key/tests/known_hosts.rs
ssh-key/tests/private_key.rs
ssh-key/tests/public_key.rs

Extracts a type which models the concerns of comments, namely that they can be encoded as an RFC4251 `string` type which can hold arbitrary binary data when stored in the binary serialization of a private key.
This replaces the various accessor methods on `PublicKey` and `PrivateKey` for handling the various conversions.

ssh-key: extract a `Comment` type

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/decryptor.rs
ssh-cipher/src/encryptor.rs
ssh-cipher/src/lib.rs
ssh-encoding/Cargo.toml
ssh-encoding/src/error.rs
ssh-encoding/src/lib.rs
ssh-encoding/src/mpint.rs
ssh-key/Cargo.toml
ssh-key/src/certificate/builder.rs
ssh-key/src/error.rs
ssh-key/src/kdf.rs
ssh-key/src/private.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/ed25519.rs
ssh-key/src/private/rsa.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/rsa.rs
ssh-key/src/signature.rs
ssh-key/tests/encrypted_private_key.rs
ssh-protocol/src/lib.rs

This notably includes `dsa` and `rsa` upgrades which migrate to `crypto-bigint`, allowing us to drop `num-bigint-dig` as a dependency

Use `rc.*` crate prereleases

---

.github/workflows/ssh-key.yml
Cargo.lock
Cargo.toml
ssh-key/Cargo.toml
ssh-key/src/lib.rs
ssh-key/tests/certificate.rs
ssh-key/tests/certificate_builder.rs
ssh-key/tests/private_key.rs
ssh-key/tests/sshsig.rs

This reverts commit 20e7954e3378d997090b46423e843a1b0b67ec33.
Now that #367 is merged and `ssh-key` v0.7.0-rc.0 is released, restores the `ed25519` feature.

Revert "ssh-key: temporarily remove `ed25519` feature (#366)"

---

ssh-cipher/src/chacha20poly1305.rs
ssh-cipher/src/lib.rs

Replaces the inherent method-based API with an `AeadInOut` trait impl.
AAD is supported up to lengths of 16 (i.e. the Poly1305 block size).
This is sufficient to cover the relevant use cases for OpenSSH, which are empty AAD or AAD with a length of 4 (i.e. encrypted `uint32` length).

ssh-cipher: impl `AeadInOut` for `ChaCha20Poly1305`

---

ssh-cipher/tests/lib.rs

Adds a basic round trip encryption test for all supported ciphers

ssh-cipher: add round trip test

---

ssh-cipher/src/chacha20poly1305.rs

Try all combinations of AAD and plaintext lengths up to the Poly1305 block size

ssh-cipher: improve `Poly1305` tests

---

ssh-key/src/lib.rs

Provides access to the `ssh-cipher` and `ssh-encoding` crates

ssh-key: re-export `cipher` and `encoding`

---

ssh-key/src/dot_ssh.rs
ssh-key/src/private.rs
ssh-key/src/private/dsa.rs
ssh-key/src/private/ecdsa.rs
ssh-key/src/private/opaque.rs
ssh-key/src/public.rs

- Implemented `From` and `TryFrom` traits so that `DsaPrivateKey`, `EcdsaPrivateKey`, and `OpaquePrivateKeyBytes` can be created from bytes without needing the `encoding::Decode` trait (`ssh-key` doesn't export `ssh-encoding`, so I had some issues with this).
- Implemented functions for `PrivateKey` and `PublicKey` using `std::io::{Write, Read}` traits (std only). This allows you to read / write files without needing to provide a path
- Use `AsRef<Path>` instead of `&Path` for `PrivateKey` and `PublicKey`
I'd appreciate it if this could be back-ported to `0.6.x`. The `v0.7.0-rc.0` release isn't working for me.

Use Traits

---

ssh-key/src/public.rs

Suggest using Digest for large messages in PublicKey::verify()

---

Cargo.lock
ssh-encoding/Cargo.toml
ssh-encoding/src/lib.rs
ssh-encoding/src/mpint.rs
ssh-key/Cargo.toml
ssh-key/src/private/dsa.rs
ssh-key/src/private/rsa.rs
ssh-key/src/public/dsa.rs
ssh-key/src/public/rsa.rs
ssh-key/src/signature.rs

...and all of the downstream dependencies needed to upgrade it:
- `dsa`
- `rsa`
- `p256`
- `p384`
- `p521`
This notably includes some changes to `dsa` and `rsa` which eliminate the use of `Odd` and `NonZero` input parameters, putting those checks in the constructor instead.

Bump `crypto-bigint` to v0.7.0-pre.5

---

ssh-key/src/private.rs
ssh-key/src/public.rs

- Replace Generics with `impl` for consistency
- Make File + Path functions use `Read` + `Write` implementations to unify behavior
- Unified Unix + Non-Unix behavior for `PrivateKey::write_openssh_file`

ssh-key: Consistency in Key Read + Write

---

Cargo.lock
ssh-key/Cargo.toml

These merely pulled in extra dependencies, as opposed to activating needed functionality

ssh-key: remove unnecessary `std` feature activations

---

Cargo.lock
ssh-cipher/Cargo.toml
ssh-cipher/src/chacha20poly1305.rs
ssh-encoding/Cargo.toml
ssh-encoding/tests/derive.rs
ssh-key/Cargo.toml

This commit bumps pretty much every algorithm dependency to the latest versions, which have switched from `hybrid-array` v0.3 to v0.4.

Bump `hybrid-array` to v0.4
